/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo2

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    val ids = listOf(1, 2, 3)
    val items = mapOf(
        1 to listOf(
            Item(1, "アイテム1", Rarity.N, 100),
            Item(2, "アイテム2", Rarity.N, 100),
            Item(3, "アイテム3", Rarity.N, 100),
            Item(4, "アイテム4", Rarity.R, 50),
            Item(5, "アイテム5", Rarity.SR, 10)
        ),
        2 to listOf(
            Item(6, "アイテム6", Rarity.N, 100),
            Item(7, "アイテム7", Rarity.N, 100),
            Item(8, "アイテム8", Rarity.N, 100),
            Item(9, "アイテム9", Rarity.R, 50),
            Item(10, "アイテム10", Rarity.SR, 10)
        ),
        3 to listOf(
            Item(11, "アイテム11", Rarity.N, 50),
            Item(12, "アイテム12", Rarity.R, 30),
            Item(13, "アイテム13", Rarity.SR, 15),
            Item(14, "アイテム14", Rarity.SSR, 5),
        )
    )
    val gacha = Gacha(ids, items)

    println("ids: ${gacha.listIds()}")

    println("draw1: ${gacha.draw(1)}")
    println("draw2: ${gacha.draw(2)}")
    println("draw3: ${gacha.draw(3)}")

    println("drawRandom: ${gacha.drawRandom()}")

    println("list1: ${gacha.list(1)}")
    println("list2: ${gacha.list(2)}")
    println("list3: ${gacha.list(3)}")
}
